'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ChevronLeft, ChevronRight, Minus, Plus, Mic, Pause, Play, RotateCcw, X } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import MapArt, { type Room } from './map-art';

type Recognition = {lang:string;continuous:boolean;interimResults:boolean;start:()=>void;abort:()=>void;onresult:((e:{results:{transcript:string}[][]})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null};
const rooms:{id:Room;name:string;section:string;number:string}[]=[{id:'about',name:'The Great Hall',section:'My story',number:'I'},{id:'research',name:'Astronomy Tower',section:'Research',number:'II'},{id:'writing',name:'The Library',section:'Writing',number:'III'},{id:'beyond',name:'Common Room',section:'Beyond the work',number:'IV'},{id:'contact',name:'The Owlery',section:'Let’s talk',number:'V'}];
const interests=['Sample efficiency','Continual learning','Human simulation','Mechanistic interpretability + RL','World models & neural RL environments','Sycophancy & adaptive reasoning'];
function RoomContents({room}:{room:Room}){
 if(room==='about')return <><p className="letter-intro">Hello, I’m Sriraam.</p><p>I’m an Applied Researcher on the post-training team at <a href="https://www.chakra.dev/" target="_blank" rel="noreferrer">Chakra Labs ↗</a>. I build RL environments, training tasks, and internal benchmarks for foundation labs, with a focus on knowledge work.</p><p>Studying Learning Science at <a href="https://www.gse.harvard.edu/" target="_blank" rel="noreferrer">Harvard ↗</a> shaped the way I see the world: almost every problem is a learning problem. Human learning continues to inspire my reinforcement learning work.</p><p className="handwritten">Always a student. Occasionally a marauder.</p></>;
 if(room==='research')return <><p className="letter-intro">How do we learn to learn?</p><p>I’m interested in what makes learning efficient, adaptable, and a little more human.</p><ul className="research-list">{interests.map((v,i)=><li key={v}><span>0{i+1}</span>{v}</li>)}</ul><a className="letter-link" href="https://x.com/27upon2" target="_blank" rel="noreferrer">Thinking about these questions too? Let’s talk <ArrowUpRight size={17}/></a></>;
 if(room==='writing')return <><p className="letter-intro">Notes from the experiments.</p><a className="article-card" href="https://www.sriraam.me/blog/vibe-rl" target="_blank" rel="noreferrer"><span className="eyebrow">FIELD NOTES · 5 MARCH 2026</span><h3>My first Vibe RL experience <ArrowUpRight size={23}/></h3><p>Using Prime Intellect and Codex to train Qwen3-4B to make better ASCII diagrams. A record of experiments, reward hacking, and what I learned along the way.</p><span className="read-story">Read the story ⟶</span></a><a className="letter-link" href="https://www.sriraam.me/blog" target="_blank" rel="noreferrer">All writing <ArrowUpRight size={17}/></a></>;
 if(room==='beyond')return <><p className="letter-intro">Not all curiosity is research.</p><p>Some of it leads to Hogwarts. Some to anime. Some to a very good K-drama.</p><div className="interests"><span>Hogwarts</span><span>Anime</span><span>K-dramas</span></div><blockquote>“What I cannot create, I do not understand.”<cite>— Richard Feynman</cite></blockquote></>;
 return <><p className="letter-intro">Send an owl.</p><p>If you’re thinking about learning, reinforcement learning, or any of the questions in the Astronomy Tower, I’d love to talk to you.</p><div className="contact-links"><a href="https://x.com/27upon2" target="_blank" rel="noreferrer"><span>X / Twitter<small>@27upon2</small></span><ArrowUpRight/></a><a href="https://github.com/13point5" target="_blank" rel="noreferrer"><span>GitHub<small>13point5</small></span><ArrowUpRight/></a><a href="https://www.linkedin.com/in/13point5" target="_blank" rel="noreferrer"><span>LinkedIn<small>Sriraam</small></span><ArrowUpRight/></a></div></>;
}
export default function Home(){
 const [open,setOpen]=useState(false),[opening,setOpening]=useState(false),[room,setRoom]=useState<Room|null>(null),[left,setLeft]=useState(false),[right,setRight]=useState(false),[zoom,setZoom]=useState(1),[paused,setPaused]=useState(false),[listening,setListening]=useState(false),[voiceMessage,setVoiceMessage]=useState(''),[speechAvailable,setSpeechAvailable]=useState(false);
 const speech=useRef<Recognition|null>(null),viewport=useRef<HTMLDivElement>(null),firstNav=useRef<HTMLButtonElement>(null),unfoldButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>{setSpeechAvailable(Boolean((window as unknown as {SpeechRecognition?:unknown;webkitSpeechRecognition?:unknown}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:unknown}).webkitSpeechRecognition));const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');setPaused(reduced.matches);return()=>speech.current?.abort()},[]);
 useEffect(()=>{if(!opening)return;const id=setTimeout(()=>{setOpening(false);firstNav.current?.focus({preventScroll:true})},1500);return()=>clearTimeout(id)},[opening]);
 useEffect(()=>{if(open&&viewport.current)viewport.current.scrollLeft=(viewport.current.scrollWidth-viewport.current.clientWidth)/2},[open,zoom]);
 function reveal(){speech.current?.abort();setListening(false);setVoiceMessage('');setOpen(true);setOpening(true)}
 function fold(){setRoom(null);setOpen(false);setOpening(false);setLeft(false);setRight(false);setZoom(1);setTimeout(()=>unfoldButton.current?.focus(),0)}
 function visit(id:Room){if(id==='contact')setLeft(true);if(id==='research'||id==='writing')setRight(true);setRoom(id)}
 function listen(){if(listening){speech.current?.abort();setListening(false);return}const Constructor=(window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>Recognition}).webkitSpeechRecognition;if(!Constructor){setVoiceMessage('Voice isn’t available in this browser. Click the words to unfold.');return}const recognition=new Constructor();speech.current=recognition;recognition.lang='en-US';recognition.continuous=false;recognition.interimResults=false;recognition.onresult=e=>{const said=Array.from(e.results).map(r=>r[0].transcript).join(' ').toLowerCase();if(said.includes('mischief managed'))reveal();else setVoiceMessage('The map is listening for “Mischief Managed”. Try again, or click the words.')};recognition.onerror=e=>{setListening(false);setVoiceMessage(e.error==='not-allowed'?'Microphone access wasn’t granted. You can still click the words to unfold.':'The spell wasn’t heard. Try again, or click the words to unfold.')};recognition.onend=()=>setListening(false);setVoiceMessage('Say “Mischief Managed”…');try{recognition.start();setListening(true)}catch{setVoiceMessage('Voice couldn’t start. Click the words to unfold.');setListening(false)}}
 const selected=rooms.find(r=>r.id===room);
 return <main className={`experience ${open?'is-open':''} ${opening?'is-opening':''}`}>
 <header className="topbar"><a href="https://www.sriraam.me/" title="Sriraam’s original website">S R I R A A M <span>— a map of the mind</span></a>{open?<button className="fold-all" onClick={fold}><RotateCcw size={14}/> Fold the map</button>:<span className="edition">A PERSONAL CARTOGRAPHY · No. 013½</span>}</header>
 {(!open||opening)&&<section className={`cover-stage ${opening?'cover-opening':''}`} aria-hidden={opening} inert={opening}>
 <div className="cover-stack"><button ref={unfoldButton} className="original-cover" onClick={reveal} aria-label="Unfold the Marauder’s Map"><span className="cover-leaf leaf-left"><img src="/images/original-map.jpg" alt="Original Marauder’s Map: Hogwarts School of Witchcraft & Wizardry"/></span><span className="cover-leaf leaf-right" aria-hidden="true"><img src="/images/original-map.jpg" alt=""/></span><span className="cover-fold"/></button></div>
 <div className="incantation"><p>Some things are only revealed to the curious.</p><button className="spell" onClick={reveal}>Mischief Managed <span>⟶</span></button><div className="voice-line"><span>CLICK THE WORDS{speechAvailable?' OR':''}</span>{speechAvailable&&<button onClick={listen} className={listening?'listening':''} aria-pressed={listening}><Mic size={13}/>{listening?'LISTENING…':'SPEAK THE SPELL'}</button>}</div><p className="voice-status" role="status">{voiceMessage}</p></div>
 </section>}
 {open&&<section className="map-stage" aria-label="Explore the map" inert={opening}>
 <nav className="room-nav" aria-label="Places on the map">{rooms.map((r,i)=><button ref={i===0?firstNav:undefined} key={r.id} onClick={()=>visit(r.id)}><span>{r.number}</span>{r.section}</button>)}</nav>
 <div className="map-viewport" ref={viewport}><div className="map-paper" style={{width:`max(${1050*zoom}px, ${100*zoom}%)`}}>
 <div className="paper-grain"/><MapArt onVisit={visit} paused={paused||opening}/><div className="map-creases"/>
 <div className={`wing wing-left ${left?'unfolded':''}`}><div className="wing-cover"><img src="/images/original-map.jpg" alt=""/><span className="wing-words">Porticus Occidentalis</span></div><button onClick={()=>setLeft(!left)} aria-expanded={left} className="wing-tab">{left?<ChevronRight size={16}/>:<ChevronLeft size={16}/>}<span>{left?'Fold':'Unfold'} west wing</span></button></div>
 <div className={`wing wing-right ${right?'unfolded':''}`}><div className="wing-cover"><img src="/images/original-map.jpg" alt=""/><span className="wing-words">Porticus Orientalis</span></div><button onClick={()=>setRight(!right)} aria-expanded={right} className="wing-tab"><span>{right?'Fold':'Unfold'} east wing</span>{right?<ChevronLeft size={16}/>:<ChevronRight size={16}/>}</button></div>
 </div></div>
 <div className="map-controls"><p><span className="live-dot"/> {paused?'The castle is still.':'The castle is never quite still.'}<span className="desktop-hint"> Select a room or follow the footsteps.</span></p><div className="control-buttons"><button onClick={()=>setPaused(!paused)} aria-label={paused?'Resume footsteps':'Pause footsteps'} title={paused?'Resume footsteps':'Pause footsteps'}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><span className="control-divider"/><button onClick={()=>setZoom(z=>Math.max(1,+(z-.25).toFixed(2)))} disabled={zoom<=1} aria-label="Zoom out"><Minus size={16}/></button><button className="zoom-value" onClick={()=>setZoom(1)} aria-label="Reset zoom">{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>Math.min(2,+(z+.25).toFixed(2)))} disabled={zoom>=2} aria-label="Zoom in"><Plus size={16}/></button></div></div>
 </section>}
 <footer className="footer"><span>{open?'Hogwarts, by way of a curious mind.':'For the incurably curious.'}</span><a href="https://minalima.com/shop-wizarding-world/shop-by-collection/the-marauders-map/" target="_blank" rel="noreferrer">Map artwork by MinaLima ↗</a></footer>
 <Dialog open={room!==null} onOpenChange={value=>{if(!value)setRoom(null)}}><DialogContent className="map-letter" showCloseButton={false}><button className="letter-close" aria-label="Return to the map" onClick={()=>setRoom(null)}><X size={20}/></button><span className="letter-kicker">{selected?.number} · A ROOM ON THE MAP</span><DialogTitle className="letter-title">{selected?.name}</DialogTitle><DialogDescription className="letter-description">{selected?.section}</DialogDescription><div className="letter-ornament">✧</div><div className="letter-body">{room&&<RoomContents room={room}/>}</div><button className="back-map" onClick={()=>setRoom(null)}>← Return to the map</button></DialogContent></Dialog>
 </main>
}
