"""Reusable attachment metadata. Authored letters use their pen trajectories;
sampled capitals use explicitly chosen stem hints, registered to actual ink.
No glyph contours are modified. Run prepare-reconstruction-glyphs.mjs first.
"""
import json, math
from pathlib import Path
import numpy as np
import cv2
root=Path(__file__).resolve().parents[1]
namespace={'__file__':str(root/'scripts/build-complete-kits.py')}
exec((root/'scripts/build-complete-kits.py').read_text().split('kit=json.loads')[0],namespace)
kit=json.loads((root/'app/letter-kit/glyphs.json').read_text())
hints={'B':(.23,.83,0,1),'D':(.25,.83,0,1),'E':(.25,.83,0,1),'E.alt':(.25,.83,0,1),'I':(.45,.82,0,1),'M':(.85,.8,.3,1),'N':(.13,.78,-.15,1),'R':(.82,.8,.9,.25),'S':(.84,.22,.15,1),'T':(.46,.82,0,1),'V':(.18,.2,-.5,-1),'V.alt':(.18,.2,-.5,-1)}
result={'capitals':{},'script':{}}
def recipe_port(path,arch=False):
 pen=namespace['SamplePen']();namespace['parse_path'](path,pen);pen._endPath()
 # A starts at the foot of its left leg; other letters extend the last
 # point of their principal stroke. Closed bowls extend from their seam.
 pts=np.array(pen.strokes[0]);pts=pts if arch and path.startswith('M8 96') else pts[::-1]
 lengths=np.linalg.norm(np.diff(pts,axis=0),axis=1).cumsum();idx=min(len(pts)-1,int(np.searchsorted(lengths,5))+1)
 p=pts[idx];v=pts[0]-p;v/=np.linalg.norm(v)
 if arch:
  _,b=namespace['outline'](path,True);scale=100/(b[3]-b[1]);p=(p-np.array(b[:2]))*scale
 return p,v
for g in kit:
 name=g['id'];mask=cv2.imread(str(root/f'outputs/reconstruction/templates/{name}.png'),cv2.IMREAD_UNCHANGED)
 mask=mask[:,:,-1] if mask.ndim==3 else mask
 sy=mask.shape[0]/100;sx=mask.shape[1]/g['width']
 if name in namespace['cap']:p,v=recipe_port(namespace['cap'][name][1],True)
 else:
  x,y,dx,dy=hints[name];p=np.array([x*g['width'],y*100]);v=np.array([dx,dy],dtype=float);v/=np.linalg.norm(v)
 # Register sampled stem hints to the nearest substantial interior pixel.
 dist=cv2.distanceTransform((mask>128).astype(np.uint8),cv2.DIST_L2,5)
 yy,xx=np.where(dist>1.3);points=np.stack([xx/sx,yy/sy],axis=1)
 if name in hints:p=points[np.argmin(np.linalg.norm(points-p,axis=1))]
 normal=np.array([-v[1],v[0]])
 def ink(q):
  x,y=np.round(q*np.array([sx,sy])).astype(int)
  return 0<=y<mask.shape[0] and 0<=x<mask.shape[1] and mask[y,x]>128
 assert ink(p),name
 sides=[]
 for sign in [-1,1]:
  a=.2
  while a<30 and ink(p+normal*a*sign):a+=.2
  sides.append(a)
 # Symmetric root stays within the existing stem; blend outward to pen width.
 width=max(1.2,2*min(sides)*.85)
 result['capitals'][name]={'x':round(float(p[0]),4),'y':round(float(p[1]),4),'dx':round(float(v[0]),6),'dy':round(float(v[1]),6),'width':round(width,3)}
for name,(_,path) in {**namespace['lower'],**namespace['upper']}.items():
 p,v=recipe_port(path);normal=np.array([-v[1],v[0]]);nib=np.array([math.cos(-32*math.pi/180),math.sin(-32*math.pi/180)])
 width=2*math.sqrt((3.6*np.dot(normal,nib))**2+(1.05*np.dot(normal,[-nib[1],nib[0]]))**2)
 result['script'][name]={'x':round(float(p[0]),4),'y':round(float(p[1]),4),'dx':round(float(v[0]),6),'dy':round(float(v[1]),6),'width':round(width,3)}
(root/'app/letter-kit/stroke-ports.ts').write_text('// Generated by scripts/build-stroke-ports.py. Glyph-local pen continuations.\nexport const strokePorts = '+json.dumps(result,indent=1)+';\n')
print('Registered',len(result['capitals']),'capital and',len(result['script']),'script stroke ports')
